var wms_layers = [];


        var lyr_ESRIGraylight_0 = new ol.layer.Tile({
            'title': 'ESRI Gray (light)',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}'
            })
        });
var format_ParentsNotAttendingCollege_1 = new ol.format.GeoJSON();
var features_ParentsNotAttendingCollege_1 = format_ParentsNotAttendingCollege_1.readFeatures(json_ParentsNotAttendingCollege_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ParentsNotAttendingCollege_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ParentsNotAttendingCollege_1.addFeatures(features_ParentsNotAttendingCollege_1);
var lyr_ParentsNotAttendingCollege_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ParentsNotAttendingCollege_1, 
                style: style_ParentsNotAttendingCollege_1,
                popuplayertitle: 'Parents Not Attending College',
                interactive: true,
    title: 'Parents Not Attending College<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_0.png" /> 0 - 124<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_1.png" /> 124 - 360<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_2.png" /> 360 - 641<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_3.png" /> 641 - 1032<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_4.png" /> 1032 - 1633<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_5.png" /> 1633 - 2476<br />\
    <img src="styles/legend/ParentsNotAttendingCollege_1_6.png" /> 2476 - 3972<br />' });
var format_UndergraduateParentsUtilizingChildcare_2 = new ol.format.GeoJSON();
var features_UndergraduateParentsUtilizingChildcare_2 = format_UndergraduateParentsUtilizingChildcare_2.readFeatures(json_UndergraduateParentsUtilizingChildcare_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_UndergraduateParentsUtilizingChildcare_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_UndergraduateParentsUtilizingChildcare_2.addFeatures(features_UndergraduateParentsUtilizingChildcare_2);
var lyr_UndergraduateParentsUtilizingChildcare_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_UndergraduateParentsUtilizingChildcare_2, 
                style: style_UndergraduateParentsUtilizingChildcare_2,
                popuplayertitle: 'Undergraduate Parents Utilizing Childcare',
                interactive: true,
    title: 'Undergraduate Parents Utilizing Childcare<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_0.png" /> 0 - 1<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_1.png" /> 1 - 3<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_2.png" /> 3 - 6<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_3.png" /> 6 - 10<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_4.png" /> 10 - 16<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_5.png" /> 16 - 24<br />\
    <img src="styles/legend/UndergraduateParentsUtilizingChildcare_2_6.png" /> 24 - 36<br />' });
var format_UndergraduateParentswithChildren_3 = new ol.format.GeoJSON();
var features_UndergraduateParentswithChildren_3 = format_UndergraduateParentswithChildren_3.readFeatures(json_UndergraduateParentswithChildren_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_UndergraduateParentswithChildren_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_UndergraduateParentswithChildren_3.addFeatures(features_UndergraduateParentswithChildren_3);
var lyr_UndergraduateParentswithChildren_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_UndergraduateParentswithChildren_3, 
                style: style_UndergraduateParentswithChildren_3,
                popuplayertitle: 'Undergraduate Parents with Children',
                interactive: true,
    title: 'Undergraduate Parents with Children<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_0.png" /> 0 - 7<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_1.png" /> 7 - 24<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_2.png" /> 24 - 51<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_3.png" /> 51 - 94<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_4.png" /> 94 - 146<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_5.png" /> 146 - 204<br />\
    <img src="styles/legend/UndergraduateParentswithChildren_3_6.png" /> 204 - 281<br />' });
var format_ACCCampuses_4 = new ol.format.GeoJSON();
var features_ACCCampuses_4 = format_ACCCampuses_4.readFeatures(json_ACCCampuses_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ACCCampuses_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ACCCampuses_4.addFeatures(features_ACCCampuses_4);
var lyr_ACCCampuses_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ACCCampuses_4, 
                style: style_ACCCampuses_4,
                popuplayertitle: 'ACC Campuses',
                interactive: false,
                title: '<img src="styles/legend/ACCCampuses_4.png" /> ACC Campuses'
            });

lyr_ESRIGraylight_0.setVisible(true);lyr_ParentsNotAttendingCollege_1.setVisible(true);lyr_UndergraduateParentsUtilizingChildcare_2.setVisible(true);lyr_UndergraduateParentswithChildren_3.setVisible(true);lyr_ACCCampuses_4.setVisible(true);
var layersList = [lyr_ESRIGraylight_0,lyr_ParentsNotAttendingCollege_1,lyr_UndergraduateParentsUtilizingChildcare_2,lyr_UndergraduateParentswithChildren_3,lyr_ACCCampuses_4];
lyr_ParentsNotAttendingCollege_1.set('fieldAliases', {'fid': 'fid', 'GISJOIN': 'GISJOIN', 'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'GEOIDFQ': 'GEOIDFQ', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'ORIG_FID': 'ORIG_FID', 'Join_fid': 'Join_fid', 'Join_GISJOIN.t': 'Join_GISJOIN.t', 'Join_COUNTYA.t': 'Join_COUNTYA.t', 'Join_total_children_0_17.t': 'Join_total_children_0_17.t', 'Join_children_0_14.t': 'Join_children_0_14.t', 'Join_enrolled_undergrad_b14002_all_adults.t': 'Join_enrolled_undergrad_b14002_all_adults.t', 'Join_enrolled_grad_b14002_all_adults.t': 'Join_enrolled_grad_b14002_all_adults.t', 'Join_own_children_under_18.t': 'Join_own_children_under_18.t', 'Join_own_children_under_12.t': 'Join_own_children_under_12.t', 'Join_TRACTCE': 'Join_TRACTCE', 'Join_GEOID': 'Join_GEOID', 'Join_PUMACE20': 'Join_PUMACE20', 'Join_pct_college_households_using_childcare.p': 'Join_pct_college_households_using_childcare.p', 'Join_undergrad_parents_0_12.p': 'Join_undergrad_parents_0_12.p', 'Join_undergrad_parents_0_12_using_childcare.p': 'Join_undergrad_parents_0_12_using_childcare.p', 'Join_tract_est_parents_0_12_attending_college.c': 'Join_tract_est_parents_0_12_attending_college.c', 'Join_tract_est_parents_0_12_not_attending_college.c': 'Join_tract_est_parents_0_12_not_attending_college.c', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'Join_tract_est_parents_0_12_no_college_not_enrolled.c', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'Join_tract_est_parents_0_12_some_college_not_enrolled.c', 'Join_tract_est_parents_0_12_using_child_care.c': 'Join_tract_est_parents_0_12_using_child_care.c', 'Join_tract_est_children_with_college_parent.c': 'Join_tract_est_children_with_college_parent.c', 'Join_tract_est_parent_undergrad_child_0_12.c': 'Join_tract_est_parent_undergrad_child_0_12.c', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'Join_tract_est_parents_no_college_some_college_child_0_12.c', 'Join_tract_est_undergrad_parents_0_12.c': 'Join_tract_est_undergrad_parents_0_12.c', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'Join_tract_est_undergrad_parents_0_12_using_childcare.c', 'Join_prop_parents_undergrad_with_childcare': 'Join_prop_parents_undergrad_with_childcare', 'undergrad_parents_est': 'undergrad_parents_est', 'parents_no_some_college': 'parents_no_some_college', 'student_parents_childcare': 'student_parents_childcare', });
lyr_UndergraduateParentsUtilizingChildcare_2.set('fieldAliases', {'fid': 'fid', 'GISJOIN': 'GISJOIN', 'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'GEOIDFQ': 'GEOIDFQ', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'ORIG_FID': 'ORIG_FID', 'Join_fid': 'Join_fid', 'Join_GISJOIN.t': 'Join_GISJOIN.t', 'Join_COUNTYA.t': 'Join_COUNTYA.t', 'Join_total_children_0_17.t': 'Join_total_children_0_17.t', 'Join_children_0_14.t': 'Join_children_0_14.t', 'Join_enrolled_undergrad_b14002_all_adults.t': 'Join_enrolled_undergrad_b14002_all_adults.t', 'Join_enrolled_grad_b14002_all_adults.t': 'Join_enrolled_grad_b14002_all_adults.t', 'Join_own_children_under_18.t': 'Join_own_children_under_18.t', 'Join_own_children_under_12.t': 'Join_own_children_under_12.t', 'Join_TRACTCE': 'Join_TRACTCE', 'Join_GEOID': 'Join_GEOID', 'Join_PUMACE20': 'Join_PUMACE20', 'Join_pct_college_households_using_childcare.p': 'Join_pct_college_households_using_childcare.p', 'Join_undergrad_parents_0_12.p': 'Join_undergrad_parents_0_12.p', 'Join_undergrad_parents_0_12_using_childcare.p': 'Join_undergrad_parents_0_12_using_childcare.p', 'Join_tract_est_parents_0_12_attending_college.c': 'Join_tract_est_parents_0_12_attending_college.c', 'Join_tract_est_parents_0_12_not_attending_college.c': 'Join_tract_est_parents_0_12_not_attending_college.c', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'Join_tract_est_parents_0_12_no_college_not_enrolled.c', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'Join_tract_est_parents_0_12_some_college_not_enrolled.c', 'Join_tract_est_parents_0_12_using_child_care.c': 'Join_tract_est_parents_0_12_using_child_care.c', 'Join_tract_est_children_with_college_parent.c': 'Join_tract_est_children_with_college_parent.c', 'Join_tract_est_parent_undergrad_child_0_12.c': 'Join_tract_est_parent_undergrad_child_0_12.c', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'Join_tract_est_parents_no_college_some_college_child_0_12.c', 'Join_tract_est_undergrad_parents_0_12.c': 'Join_tract_est_undergrad_parents_0_12.c', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'Join_tract_est_undergrad_parents_0_12_using_childcare.c', 'Join_prop_parents_undergrad_with_childcare': 'Join_prop_parents_undergrad_with_childcare', 'undergrad_parents_est': 'undergrad_parents_est', 'parents_no_some_college': 'parents_no_some_college', 'student_parents_childcare': 'student_parents_childcare', });
lyr_UndergraduateParentswithChildren_3.set('fieldAliases', {'fid': 'fid', 'GISJOIN': 'GISJOIN', 'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'GEOIDFQ': 'GEOIDFQ', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'ORIG_FID': 'ORIG_FID', 'Join_fid': 'Join_fid', 'Join_GISJOIN.t': 'Join_GISJOIN.t', 'Join_COUNTYA.t': 'Join_COUNTYA.t', 'Join_total_children_0_17.t': 'Join_total_children_0_17.t', 'Join_children_0_14.t': 'Join_children_0_14.t', 'Join_enrolled_undergrad_b14002_all_adults.t': 'Join_enrolled_undergrad_b14002_all_adults.t', 'Join_enrolled_grad_b14002_all_adults.t': 'Join_enrolled_grad_b14002_all_adults.t', 'Join_own_children_under_18.t': 'Join_own_children_under_18.t', 'Join_own_children_under_12.t': 'Join_own_children_under_12.t', 'Join_TRACTCE': 'Join_TRACTCE', 'Join_GEOID': 'Join_GEOID', 'Join_PUMACE20': 'Join_PUMACE20', 'Join_pct_college_households_using_childcare.p': 'Join_pct_college_households_using_childcare.p', 'Join_undergrad_parents_0_12.p': 'Join_undergrad_parents_0_12.p', 'Join_undergrad_parents_0_12_using_childcare.p': 'Join_undergrad_parents_0_12_using_childcare.p', 'Join_tract_est_parents_0_12_attending_college.c': 'Join_tract_est_parents_0_12_attending_college.c', 'Join_tract_est_parents_0_12_not_attending_college.c': 'Join_tract_est_parents_0_12_not_attending_college.c', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'Join_tract_est_parents_0_12_no_college_not_enrolled.c', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'Join_tract_est_parents_0_12_some_college_not_enrolled.c', 'Join_tract_est_parents_0_12_using_child_care.c': 'Join_tract_est_parents_0_12_using_child_care.c', 'Join_tract_est_children_with_college_parent.c': 'Join_tract_est_children_with_college_parent.c', 'Join_tract_est_parent_undergrad_child_0_12.c': 'Join_tract_est_parent_undergrad_child_0_12.c', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'Join_tract_est_parents_no_college_some_college_child_0_12.c', 'Join_tract_est_undergrad_parents_0_12.c': 'Join_tract_est_undergrad_parents_0_12.c', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'Join_tract_est_undergrad_parents_0_12_using_childcare.c', 'Join_prop_parents_undergrad_with_childcare': 'Join_prop_parents_undergrad_with_childcare', 'undergrad_parents_est': 'undergrad_parents_est', 'parents_no_some_college': 'parents_no_some_college', 'student_parents_childcare': 'student_parents_childcare', });
lyr_ACCCampuses_4.set('fieldAliases', {'X': 'X', 'Y': 'Y', 'fid': 'fid', 'ACC': 'ACC', 'Name': 'Name', 'Zip': 'Zip', 'County': 'County', 'Operation': 'Operation', 'Type': 'Type', 'Capacity': 'Capacity', 'Age Levels': 'Age Levels', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Coordinate': 'Coordinate', 'Street Add': 'Street Add', 'Services': 'Services', 'Hours': 'Hours', 'Instructio': 'Instructio', });
lyr_ParentsNotAttendingCollege_1.set('fieldImages', {'fid': 'TextEdit', 'GISJOIN': 'TextEdit', 'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'GEOIDFQ': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'ORIG_FID': 'TextEdit', 'Join_fid': 'TextEdit', 'Join_GISJOIN.t': 'TextEdit', 'Join_COUNTYA.t': 'TextEdit', 'Join_total_children_0_17.t': 'TextEdit', 'Join_children_0_14.t': 'TextEdit', 'Join_enrolled_undergrad_b14002_all_adults.t': 'TextEdit', 'Join_enrolled_grad_b14002_all_adults.t': 'TextEdit', 'Join_own_children_under_18.t': 'TextEdit', 'Join_own_children_under_12.t': 'TextEdit', 'Join_TRACTCE': 'TextEdit', 'Join_GEOID': 'TextEdit', 'Join_PUMACE20': 'TextEdit', 'Join_pct_college_households_using_childcare.p': 'TextEdit', 'Join_undergrad_parents_0_12.p': 'TextEdit', 'Join_undergrad_parents_0_12_using_childcare.p': 'TextEdit', 'Join_tract_est_parents_0_12_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_not_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_using_child_care.c': 'TextEdit', 'Join_tract_est_children_with_college_parent.c': 'TextEdit', 'Join_tract_est_parent_undergrad_child_0_12.c': 'TextEdit', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'TextEdit', 'Join_prop_parents_undergrad_with_childcare': 'TextEdit', 'undergrad_parents_est': 'TextEdit', 'parents_no_some_college': 'TextEdit', 'student_parents_childcare': 'TextEdit', });
lyr_UndergraduateParentsUtilizingChildcare_2.set('fieldImages', {'fid': 'TextEdit', 'GISJOIN': 'TextEdit', 'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'GEOIDFQ': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'ORIG_FID': 'TextEdit', 'Join_fid': 'TextEdit', 'Join_GISJOIN.t': 'TextEdit', 'Join_COUNTYA.t': 'TextEdit', 'Join_total_children_0_17.t': 'TextEdit', 'Join_children_0_14.t': 'TextEdit', 'Join_enrolled_undergrad_b14002_all_adults.t': 'TextEdit', 'Join_enrolled_grad_b14002_all_adults.t': 'TextEdit', 'Join_own_children_under_18.t': 'TextEdit', 'Join_own_children_under_12.t': 'TextEdit', 'Join_TRACTCE': 'TextEdit', 'Join_GEOID': 'TextEdit', 'Join_PUMACE20': 'TextEdit', 'Join_pct_college_households_using_childcare.p': 'TextEdit', 'Join_undergrad_parents_0_12.p': 'TextEdit', 'Join_undergrad_parents_0_12_using_childcare.p': 'TextEdit', 'Join_tract_est_parents_0_12_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_not_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_using_child_care.c': 'TextEdit', 'Join_tract_est_children_with_college_parent.c': 'TextEdit', 'Join_tract_est_parent_undergrad_child_0_12.c': 'TextEdit', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'TextEdit', 'Join_prop_parents_undergrad_with_childcare': 'TextEdit', 'undergrad_parents_est': 'TextEdit', 'parents_no_some_college': 'TextEdit', 'student_parents_childcare': 'TextEdit', });
lyr_UndergraduateParentswithChildren_3.set('fieldImages', {'fid': 'TextEdit', 'GISJOIN': 'TextEdit', 'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'GEOIDFQ': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'ORIG_FID': 'TextEdit', 'Join_fid': 'TextEdit', 'Join_GISJOIN.t': 'TextEdit', 'Join_COUNTYA.t': 'TextEdit', 'Join_total_children_0_17.t': 'TextEdit', 'Join_children_0_14.t': 'TextEdit', 'Join_enrolled_undergrad_b14002_all_adults.t': 'TextEdit', 'Join_enrolled_grad_b14002_all_adults.t': 'TextEdit', 'Join_own_children_under_18.t': 'TextEdit', 'Join_own_children_under_12.t': 'TextEdit', 'Join_TRACTCE': 'TextEdit', 'Join_GEOID': 'TextEdit', 'Join_PUMACE20': 'TextEdit', 'Join_pct_college_households_using_childcare.p': 'TextEdit', 'Join_undergrad_parents_0_12.p': 'TextEdit', 'Join_undergrad_parents_0_12_using_childcare.p': 'TextEdit', 'Join_tract_est_parents_0_12_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_not_attending_college.c': 'TextEdit', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'TextEdit', 'Join_tract_est_parents_0_12_using_child_care.c': 'TextEdit', 'Join_tract_est_children_with_college_parent.c': 'TextEdit', 'Join_tract_est_parent_undergrad_child_0_12.c': 'TextEdit', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12.c': 'TextEdit', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'TextEdit', 'Join_prop_parents_undergrad_with_childcare': 'TextEdit', 'undergrad_parents_est': 'TextEdit', 'parents_no_some_college': 'TextEdit', 'student_parents_childcare': 'TextEdit', });
lyr_ACCCampuses_4.set('fieldImages', {'X': 'TextEdit', 'Y': 'TextEdit', 'fid': 'TextEdit', 'ACC': 'TextEdit', 'Name': 'TextEdit', 'Zip': 'TextEdit', 'County': 'TextEdit', 'Operation': 'TextEdit', 'Type': 'TextEdit', 'Capacity': 'TextEdit', 'Age Levels': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Coordinate': 'TextEdit', 'Street Add': 'TextEdit', 'Services': 'TextEdit', 'Hours': 'TextEdit', 'Instructio': 'TextEdit', });
lyr_ParentsNotAttendingCollege_1.set('fieldLabels', {'fid': 'hidden field', 'GISJOIN': 'hidden field', 'STATEFP': 'hidden field', 'COUNTYFP': 'hidden field', 'TRACTCE': 'hidden field', 'GEOID': 'hidden field', 'GEOIDFQ': 'hidden field', 'NAME': 'hidden field', 'NAMELSAD': 'hidden field', 'MTFCC': 'hidden field', 'FUNCSTAT': 'hidden field', 'ALAND': 'hidden field', 'AWATER': 'hidden field', 'INTPTLAT': 'hidden field', 'INTPTLON': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'ORIG_FID': 'hidden field', 'Join_fid': 'hidden field', 'Join_GISJOIN.t': 'hidden field', 'Join_COUNTYA.t': 'hidden field', 'Join_total_children_0_17.t': 'hidden field', 'Join_children_0_14.t': 'hidden field', 'Join_enrolled_undergrad_b14002_all_adults.t': 'hidden field', 'Join_enrolled_grad_b14002_all_adults.t': 'hidden field', 'Join_own_children_under_18.t': 'hidden field', 'Join_own_children_under_12.t': 'hidden field', 'Join_TRACTCE': 'hidden field', 'Join_GEOID': 'hidden field', 'Join_PUMACE20': 'hidden field', 'Join_pct_college_households_using_childcare.p': 'hidden field', 'Join_undergrad_parents_0_12.p': 'hidden field', 'Join_undergrad_parents_0_12_using_childcare.p': 'hidden field', 'Join_tract_est_parents_0_12_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_not_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_using_child_care.c': 'hidden field', 'Join_tract_est_children_with_college_parent.c': 'hidden field', 'Join_tract_est_parent_undergrad_child_0_12.c': 'hidden field', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'hidden field', 'Join_prop_parents_undergrad_with_childcare': 'hidden field', 'undergrad_parents_est': 'hidden field', 'parents_no_some_college': 'no label', 'student_parents_childcare': 'hidden field', });
lyr_UndergraduateParentsUtilizingChildcare_2.set('fieldLabels', {'fid': 'hidden field', 'GISJOIN': 'hidden field', 'STATEFP': 'hidden field', 'COUNTYFP': 'hidden field', 'TRACTCE': 'hidden field', 'GEOID': 'hidden field', 'GEOIDFQ': 'hidden field', 'NAME': 'hidden field', 'NAMELSAD': 'hidden field', 'MTFCC': 'hidden field', 'FUNCSTAT': 'hidden field', 'ALAND': 'hidden field', 'AWATER': 'hidden field', 'INTPTLAT': 'hidden field', 'INTPTLON': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'ORIG_FID': 'hidden field', 'Join_fid': 'hidden field', 'Join_GISJOIN.t': 'hidden field', 'Join_COUNTYA.t': 'hidden field', 'Join_total_children_0_17.t': 'hidden field', 'Join_children_0_14.t': 'hidden field', 'Join_enrolled_undergrad_b14002_all_adults.t': 'hidden field', 'Join_enrolled_grad_b14002_all_adults.t': 'hidden field', 'Join_own_children_under_18.t': 'hidden field', 'Join_own_children_under_12.t': 'hidden field', 'Join_TRACTCE': 'hidden field', 'Join_GEOID': 'hidden field', 'Join_PUMACE20': 'hidden field', 'Join_pct_college_households_using_childcare.p': 'hidden field', 'Join_undergrad_parents_0_12.p': 'hidden field', 'Join_undergrad_parents_0_12_using_childcare.p': 'hidden field', 'Join_tract_est_parents_0_12_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_not_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_using_child_care.c': 'hidden field', 'Join_tract_est_children_with_college_parent.c': 'hidden field', 'Join_tract_est_parent_undergrad_child_0_12.c': 'hidden field', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'hidden field', 'Join_prop_parents_undergrad_with_childcare': 'hidden field', 'undergrad_parents_est': 'hidden field', 'parents_no_some_college': 'hidden field', 'student_parents_childcare': 'no label', });
lyr_UndergraduateParentswithChildren_3.set('fieldLabels', {'fid': 'hidden field', 'GISJOIN': 'hidden field', 'STATEFP': 'hidden field', 'COUNTYFP': 'hidden field', 'TRACTCE': 'hidden field', 'GEOID': 'hidden field', 'GEOIDFQ': 'hidden field', 'NAME': 'hidden field', 'NAMELSAD': 'hidden field', 'MTFCC': 'hidden field', 'FUNCSTAT': 'hidden field', 'ALAND': 'hidden field', 'AWATER': 'hidden field', 'INTPTLAT': 'hidden field', 'INTPTLON': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'ORIG_FID': 'hidden field', 'Join_fid': 'hidden field', 'Join_GISJOIN.t': 'hidden field', 'Join_COUNTYA.t': 'hidden field', 'Join_total_children_0_17.t': 'hidden field', 'Join_children_0_14.t': 'hidden field', 'Join_enrolled_undergrad_b14002_all_adults.t': 'hidden field', 'Join_enrolled_grad_b14002_all_adults.t': 'hidden field', 'Join_own_children_under_18.t': 'hidden field', 'Join_own_children_under_12.t': 'hidden field', 'Join_TRACTCE': 'hidden field', 'Join_GEOID': 'hidden field', 'Join_PUMACE20': 'hidden field', 'Join_pct_college_households_using_childcare.p': 'hidden field', 'Join_undergrad_parents_0_12.p': 'hidden field', 'Join_undergrad_parents_0_12_using_childcare.p': 'hidden field', 'Join_tract_est_parents_0_12_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_not_attending_college.c': 'hidden field', 'Join_tract_est_parents_0_12_no_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_some_college_not_enrolled.c': 'hidden field', 'Join_tract_est_parents_0_12_using_child_care.c': 'hidden field', 'Join_tract_est_children_with_college_parent.c': 'hidden field', 'Join_tract_est_parent_undergrad_child_0_12.c': 'hidden field', 'Join_tract_est_parents_no_college_some_college_child_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12.c': 'hidden field', 'Join_tract_est_undergrad_parents_0_12_using_childcare.c': 'hidden field', 'Join_prop_parents_undergrad_with_childcare': 'hidden field', 'undergrad_parents_est': 'no label', 'parents_no_some_college': 'hidden field', 'student_parents_childcare': 'hidden field', });
lyr_ACCCampuses_4.set('fieldLabels', {'X': 'no label', 'Y': 'no label', 'fid': 'no label', 'ACC': 'no label', 'Name': 'no label', 'Zip': 'no label', 'County': 'no label', 'Operation': 'no label', 'Type': 'no label', 'Capacity': 'no label', 'Age Levels': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'Coordinate': 'no label', 'Street Add': 'no label', 'Services': 'no label', 'Hours': 'no label', 'Instructio': 'no label', });
lyr_ACCCampuses_4.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});